version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./code:/code
      - ./wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./app:/var/www/html/app
      - ./.htaccess:/var/www/html/.htaccess
